### ISSUE TITLE
Failed to build tinyscaler

### ISSUE THREAD

**Issue by WilliamFlinchbaugh** [Farama-Foundation/TinyScaler#12]
I'm trying to install tinyscaler through pip install tinyscaler and it keeps failing to build wheel
I already got Visual C++ 14.0 and upgraded pip

```
Collecting tinyscaler
  Using cached tinyscaler-1.2.4.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in e:\miniconda3\lib\site-packages (from tinyscaler) (1.23.0)
Building wheels for collected packages: tinyscaler
  Building wheel for tinyscaler (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for tinyscaler (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'tinyscaler' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinyscaler
Failed to build tinyscaler
ERROR: Could not build wheels for tinyscaler, which is required to install pyproject.toml-based projects
```

**Comment by Forbu** [comment]
I have the same issue

**Comment by 222464** [comment]
Hi, I only now see this for some reason. It built on Windows for me, but let me see if I can reproduce this. Windows is often a bit tricky.

**Comment by 222464** [comment]
Unfortunately I cannot reproduce this on my Windows 10 partition. It installs fine for me, using both python 3.10 and the python from miniconda. I am guessing something is wrong with your Visual C++ 14.0 installation. Can you try installing the build tools even if you already have Visual C++? Perhaps some components are missing.

**Comment by anujshah1003** [comment]
installing Microsoft C++ Build Tools worked for me from - https://visualstudio.microsoft.com/visual-cpp-build-tools/
The solution was described here - https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst
the second solution with 94 votes

**Comment by RunnersNum40** [comment]
Building manually from source worked for me. Installing C++ Build Tools did not fix my issue.

**Comment by 222464** [comment]
There are now pre-built wheels for Windows, see #22
