### ISSUE TITLE
[Question] Confused about using it.

### ISSUE THREAD

**Issue by ZenaMel** [Farama-Foundation/TinyScaler#20]
### Question

I'm trying to pass in an image stored on disk and overwrite it with the scaled up version, but I'm getting a `TypeError: 'float' object is not subscriptable` error.

Here's the code:

```py
    import numpy as np
    from PIL import Image
    import tinyscaler
    img = Image.open('preview.png')
    img = np.array(img).astype(np.float32)
    scaled_img = tinyscaler.scale(img, 0.5)
    scaled_img = Image.fromarray(scaled_img)
    scaled_img.save('preview.png')
```

It would be great if the readme for example just had a little snippet that shows how to go from image on disk->scale up->save to disk

**Comment by 222464** [comment]
Hi, sorry I only see this now. The scale function takes a target size as a tuple, not a scalar.
Also, to save the image with PIL, you may need to convert back to uint8.

Working code:

```python
import numpy as np
from PIL import Image
import tinyscaler
target_size = (128, 128)
img = Image.open('preview.png')
img = np.array(img).astype(np.float32) / 255.0
scaled_img = tinyscaler.scale(img, target_size)
scaled_img = Image.fromarray((scaled_img * 255.0).astype(np.uint8))
scaled_img.save('preview.png')
```

**Comment by Zenahr** [comment]
@222464 thanks a lot~! Might even make sense to add this little example to the readme?
