### ISSUE TITLE
[Bug Report] Unable to install tinyscaler 1.2.5

### ISSUE THREAD

**Issue by elliottower** [Farama-Foundation/TinyScaler#22]
**Describe the bug**
I am getting this error when running `pip install tinyscaler==1.2.5`

> ERROR: Could not find a version that satisfies the requirement tinyscaler==1.2.5 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4)
> ERROR: No matching distribution found for tinyscaler==1.2.5

I've tried upgrading pip and doing `pip install tinyscaler --upgrade` but neither worked.

Most recent version I am able to get is 1.2.4

**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

**System Info**
Describe the characteristic of your environment:
 * Describe how TinyScaler was installed (pip, docker, source, ...)
 * What OS/version you're using. 
 * Python version

**Additional context**

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/TinyScaler/issues) in the repo (**required**)

**Comment by elliottower** [comment]
It looks like there aren't any macOS distributions of tinyscaler 1.2.5, is there a reason for this?

**Comment by elliottower** [comment]
I see the issue is that there is no source distribution provided: https://pypi.org/project/tinyscaler/1.2.5/#files

**Comment by 222464** [comment]
Thanks for the report. I have uploaded the missing source distribution manually for 1.2.5, and released 1.2.6 with updated CI so it produces a source distribution + wheels for all major OS's and Python versions.

The older CI configuration used an action ([this one](https://github.com/ralfg/python-wheels-manylinux-build)) to build the wheels for Linux, but it only produced wheels, so the source distribution was missing. Now, that same Linux build job is used alongside a separate job for MacOS and Windows, as unlike those operating systems, there are many variants of Linux and therefore it requires manylinux wheels. There is a third job for the source distribution.
